### ISSUE TITLE
What is client secret and why do you want it?

### ISSUE THREAD

**Issue by nikans** [darrarski/GoogleSignIn-Swift#2]
There's no such thing in the console, and the official library does not use it.

Thanks.

**Comment by darrarski** [comment]
`CLIENT_ID` and `CLIENT_SECRET` are required by oAuth flow. You can find both in Google Developer Console, which apparently changed address to https://console.developers.google.com/

I can't help you with navigating through Google Developer Console, because I am not that familiar with it and the changes Google makes from time to time. I did however just tried it, and `CLIENT_SECRET` is definitely there. You have to create "Client ID for Web application", here is an example of how it looks like:

![Screenshot 2020-12-05 at 20 26 59](https://user-images.githubusercontent.com/1384684/101261529-504f4280-3738-11eb-9e38-6c9fc3bde011.png)
